/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectReviewApp;

import java.util.List;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
        public static void main(String[] args)
        {
        	ApplicationContext context = new ClassPathXmlApplicationContext("springbeans.xml");
        	
        	User user = context.getBean("user",User.class);
        	System.out.println("User-Name       : " +user.getUsername());
        	System.out.println("Email Id        : "+user.getEmailid());
        	System.out.println("Password        : "+user.getPassword());
        	System.out.println("Mobile Number   : "+user.getMobileno());
        	System.out.println();
        	
        	Financial_Product fp = context.getBean("product1",Financial_Product.class);
        	System.out.println("Product Id      : " +fp.getFinancial_productid());
        	System.out.println("Product Name    : "+fp.getFinancial_productname());
        	System.out.println("Description     : "+fp.getDescription());
        	System.out.println("Rating          : "+fp.getRating());
        	System.out.println();
        	System.out.println("Review Id       : "+fp.getReview().getReviewid());
        	System.out.println("Product Reviewed: " +fp.getReview().getProduct_reviewed().getFinancial_productname());
        	System.out.println("Review Text     : "+fp.getReview().getReview_text());
        	List<Comment> comments = fp.getReview().getComments();
        	System.out.println();
        	for(Comment c:comments) {
        		System.out.println("Comment Id  : "+c.getComment_id());
        		System.out.println("Comment Text: "+c.getComment_text());
        		System.out.println("Likes       : "+c.getLikes());
        		System.out.println("Dislikes    : "+c.getDislikes());
        		System.out.println("Report      : "+c.isReport());
        		System.out.println();
        	}
        }
}
